---
meta:
  github:
    org: cloudfoundry-community
    repository: traveling-cf-admin
    access_token: (( merge ))

jobs:
- name: job-traveling-cf-admin
  public: true
  serial: true
  plan:
  - aggregate:
    - get: traveling-cf-admin
      resource: repo-traveling-cf-admin
  - task: build-traveling-cf-admin
    file: traveling-cf-admin/ci/build.yml
  - put: github-release
    params:
      name: build-traveling-cf-admin/release/name
      tag: build-traveling-cf-admin/release/tag
      body: build-traveling-cf-admin/release/notes.md
      globs: [build-traveling-cf-admin/release/*.tar.gz]

resources:
- name: repo-traveling-cf-admin
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/traveling-cf-admin.git
    branch: master

- name: github-release
  type: github-release
  source:
    user: (( meta.github.org ))
    repository: (( meta.github.repository ))
    access_token: (( meta.github.access_token ))
