---
platform: linux

image: docker:///drnic/logstash-docker-pipeline

inputs:
- name: traveling-cf-admin
  path: .
- name: cf-cli-release

params:
  cf_cli_version_path: cf-cli-release/version

run:
  path: ci/build.sh
