jobs:
- name: job-traveling-cf-admin
  public: true
  serial: true
  plan:
  - aggregate:
    - get: traveling-cf-admin
      resource: git-traveling-cf-admin
  - task: build-traveling-cf-admin
    file: traveling-cf-admin/ci/build.yml
  - put: github-release
    params:
      name: build-traveling-cf-admin/release/name
      tag: build-traveling-cf-admin/release/tag
      body: build-traveling-cf-admin/release/notes.md
      globs: [build-traveling-cf-admin/release/*.tar.gz]

resources:
- name: git-traveling-cf-admin
  type: git
  source:
    uri: {{git-repository}}
    branch: {{git-branch}}

- name: github-release
  type: github-release
  source:
    user: {{github-org}}
    repository: {{github-repository}}
    access_token: {{github-access-token}}
